<template>
  <q-btn
    flat
    square
    href="mailto:Kowalski7012@gmail.com"
    color="dark"
    icon="mdi-email"
    text-color="grey-8"
    label="Contact"
    class="full-width"
    align="left"
    no-caps
  />
</template>
